config/routes.rb
Rails.application.routes.draw do

  get 'pages/home', as: 'home'
  get 'pages/about', as: 'about'

  resource :invitations, only: :create
  get 'invitations/:invite_key' => 'invitations#join', as: 'join'

  resources :projects, except: [:new] do
    resources :posts
  end

  devise_for :users, controllers: { registrations: 'registrations'}

  root 'pages#home'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member, class_name: 'User'
  belongs_to :project
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :path => ':class/:attachment/:id/:style/:filename'

   validates_attachment_content_type :image, :content_type => /\Aimage/



end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :owner, class_name: 'User'
    has_many :memberships
    has_many :members, through: :memberships
    has_many :posts

    validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  # Relation modelling the ownership of projects
  has_many :projects, foreign_key: :owner_id

  # Relation modelling the memberships in project
  has_many :memberships, foreign_key: :member_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  skip_before_action :authenticate_user!, only: :join

  def create
    emails = params[:emails].gsub(' ', '').split(',')
    project = Project.find(params[:project_id])

    InvitationMailer.invite_members(emails, project)

    flash[:notice] = 'Invitation(s) sent!'
    redirect_to project
  end

  def join
    # Simply get the invitation key form the URL, save it into the session and
    # redirect back to user sign up form
    session[:invite_key] = params[:invite_key]

    flash[:notice] = 'Welcome! Please create your account to access the project'
    redirect_to new_user_registration_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    redirect_to projects_path if user_signed_in?
  end

  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :new, :create, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def home
  end

  def index
    #@posts = Post.all.paginate(:page => params[:page], :per_page => 9)
  end

  def show
  end

  def new
    @post = @project.posts.build
  end

  def edit
  end

  def create
   @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @project, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @project, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def correct_user
      @post = current_user.posts.find_by(id:params[:id])
      redirect_to post_path, notice: "not authorized to edit this post" if @post.nil?
    end

    def post_params
      params.require(:post).permit(:description, :title, :image, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy, :show]

  def index
    @projects = current_user.projects + current_user.memberships.map(&:project)
  end

  def show
    @posts = @project.posts.order(created_at: :desc).paginate(page: params[:page], per_page: 9)
  end

  def new
  end

  def create
    # Create new project for current user
    project = current_user.projects.build(project_params)

    if project.save
      # Invite specified members
      emails = params[:project][:members].gsub(' ', '').split(',')
      InvitationMailer.invite_members(emails, project)

      redirect_to project
    else
      flash[:error] = project.errors.full_messages.join("\n")
      redirect_to projects_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def project_params
    params.require(:project).permit(:name)
  end

  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  after_filter :check_invitation

  protected
  def check_invitation
    key = session[:invite_key]
    if resource.persisted? and not key.nil?
      Membership.where(invite_key: key).update_all(member_id: resource.id)
      session.delete(:invite_key)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to raw('<span class="glyphicon glyphicon-th">
      </span> Deskus'), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deskus</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <%= render 'layouts/header' %>

    <div class="container" >
      <% flash.each do |name, msg| %>
        <% if name == 'error' %>
          <%= content_tag(:div, msg, class: 'alert alert-danger' ) %>
        <% else %>
          <%= content_tag(:div, msg, class: 'alert alert-info' ) %>
        <% end %>
      <%end%>
      <%= yield %>
    </div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">

<h1>Deskus</h1>

<h2> Talk with your team, easily. </h2>

<br>
</br>

<% if user_signed_in? %>

Welcome into your private space !

<% else %>

<p>
  <%= link_to "Sign in", new_user_session_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
<% end %>

</div>

app/views/pages/about.html.erb
<%= link_to "Home", root_path %>

<h1>About us</h1>

<h2> "La simplicité d'un groupe facebook en dehors de facebook."</h2>

<h3>
Ne mélangez pas tout. Séparez votre vie privée de votre vie publique et créez vous un espace approprié pour échanger avec votre petite équipe. Il suffit de créer un compte en 3 secondes (oui on a dit 2 en homepage mais les scientifiques divergent sur la question) - et commancez à discuter en ligne.</h3>

<h3>
C'est simple, intuitif et privé.</h3>


<h3>Bienvenue dans Deskus, votre bureau virtuel à l'abri des regards.  </h3>

app/views/pages/home.html.erb
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Deskus</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Custom Google Web Font -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

    <!-- Add custom CSS here -->
    <link href="css/landing-page.css" rel="stylesheet">

</head>

<body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://startbootstrap.com">Deskus</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#about">A Propos</a>
                    </li>
                    <li><a href="#services">Produit</a>
                    </li>
                    <li><a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Travaillez en privé.</h1>
                        <hr class="intro-divider">
                        <h3>Deskus est un espace privée en ligne pour discuter avec votre équipe.
                        </h3>
                      </br>
                      </br>
 <% if user_signed_in? %>

Welcome into your private space !

<% else %>

<p>
  <%= link_to "Sign in", new_user_session_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
<% end %>

                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->


<!DOCTYPE html>
<html lang="en">

    </div>
    <!-- /.intro-header -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Simplicité enfantine.
                        </h2>
                    <p class="lead">Ajoutez le mail de vos collaborateurs en 2 secodes. Une interface visuelle.
                    </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="/assets/ipad.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading"> 0% de compléxité
                      </h2>
                    <p class="lead"> Partagez un document, un lien, un sujet, un commentaire. </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="/assets/doge.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Vos données sont à l'abri.</h2>
                    <p class="lead">Vos données n'appartiennent ni à Facebook, ni à Microsoft, ni à Google.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="/assets/phones.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Restons en contact</h2>
                </div>
                <div class="col-lg-4">
                    <ul class="list-inline banner-social-buttons">
                        <li><a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        </div>
                        </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="#home">Accueil</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#about">A propos</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#services">Produit</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Deskus Holding Group Corp SAS Toussa Toussa 2014. All Rights Reserved: Qu'est ce que tu vas faire ? </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

</body>

</html>

app/views/posts/_form.html.erb
<%= form_for [@post.project, @post], html: { multipart: true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :project_id %>

   <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>


<%= link_to raw('<span class="glyphicon glyphicon-arrow-left">
      </span> Back'), project_path(@project) %>
      |
<%= link_to 'Show', [@project, @post] %>

app/views/posts/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="post" class= "transitions-enabled">
  <% if user_signed_in? %>
    <% @posts.each do |post| %>
      <div class="box">
        <div class="panel panel-default">
          <p><%= link_to image_tag(post.image.url(:medium)), post %></p>

          <p><strong><%= post.title %></strong></p>

          <p><%= post.description %></p>

          <p><strong><%= post.user.email if post.user %></strong></p>

          <% if post.user == current_user %>
            <div class="actions">
              <%= link_to edit_post_path(post) do %>
                <span class="glyphicon glyphicon-edit"></span>
                Edit
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="center">
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </div>

  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to raw('<span class="glyphicon glyphicon-arrow-left">
      </span> Back'), project_path(@project) %>

app/views/posts/show.html.erb
<%= link_to raw('<span class="glyphicon glyphicon-arrow-left">
      </span> Back'), project_path(@project) %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel-heading center">
  <%= image_tag @post.image.url(:medium) %>
</div>
</div>
    <div class="col-md-offset-3 col-md-6">
      <div class="panel panel-default">

        <div class="panel-heading center">
    <p>
      <strong>Title:</strong>
      <%= @post.title %>
    </p>
    <p> <%= @post.description %>
    </p>
    <p><strong><%= @post.user.email if @post.user %></p></strong>
    <% if @post.user == current_user %>
    <div>
    <%= link_to raw('<span class="glyphicon glyphicon-pencil">
      </span> Edit'), edit_project_post_path(@project, @post) %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>My Projects</h1> </br>

<div class="row">
  <div class="col-md-12">
    <div class="well">
      <%= form_for Project.new, html: { class: 'form-inline' } do |f| %>

        <div class="form-group">
          <%= f.label :name, 'New project:' %>
          <%= f.text_field :name, placeholder: 'Project Name', class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= label_tag 'project[members]', 'Invite members:' %>
          <%= text_field_tag 'project[members]', '', placeholder: 'name@email.com,   @....', class: 'form-control' %>
        </div>

        <%= f.submit 'Create', class: 'btn btn-success' %>
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ul>
      <% @projects.each do |project| %>
        <li>
          <%= link_to project.name, project %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<% if @project.owner == current_user %>
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <%= form_tag invitations_path, class: 'form-inline' do %>
          <%= hidden_field_tag 'project_id', @project.id %>

          <div class="form-group">
            <%= label_tag 'emails', 'Invite members:' %>
            <%= text_field_tag 'emails', '', placeholder: 'name@email.com, name@....', class: 'form-control' %>
          </div>

          <%= submit_tag 'Send invitations', class: 'btn btn-success' %>
        <% end %>

      </div>
    </div>
  </div>
<% end %>

<div id="post" class= "transitions-enabled">
  <div class="new-post box">
    <div class="panel panel-default">
      <%= link_to '+', new_project_post_path(@project) %>
    </div>
  </div>

  <% @posts.each do |post| %>
    <div class="box">
      <div class="panel panel-default">
        <p><%= link_to image_tag(post.image.url(:medium)), project_post_path(@project, post) %></p>

        <p><strong><%= post.title %></strong></p>

        <p><%= post.description %></p>

        <p><strong><%= post.user.email if post.user %></strong></p>

        <% if post.user == current_user %>
          <div class="actions">
            <%= link_to edit_project_post_path(@project, post) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="center">
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>